### ISSUE TITLE
How to get the vulnerable source code of cves in the dataset 

### ISSUE THREAD

**Issue by zifeng-kang** [epicosy/nexus#1]
Hi,

Nice work and I love your dataset! I am wondering if I can get a json containing the cve number together with its vulnerable source code from your dataset (not just a cve number). Is the code-level information available? Thanks!

**Comment by epicosy** [comment]
Hi Zifeng, 

It's good to know you appreciate the work. Please refer to the benchmarks at: 

- https://github.com/bqcuong/vul4j-orbis/blob/main/vul4j.orbis.yml 
- https://github.com/epicosy/cgc/blob/main/cgc.orbis.yml

Those specification files refer to the vulnerabilities and their code. 
Please feel free to reach out to me through email for more information.
